from pydantic import BaseModel
from typing import List

""" 
This data model is designed for structured outputs generated by an LLM.
It structures system goals, actors, and APIs, defining a hierarchy where 
high-level goals encompass multiple low-level goals, which in turn are 
associated with specific APIs.
"""

class DocumentDescription(BaseModel):
    description: str

class Actor(BaseModel):
    name: str
    description: str

class Actors(BaseModel):
    actors: list[Actor]

class HighLevelGoal(BaseModel):
    name: str
    description: str
    actor: Actor

class HighLevelGoals(BaseModel):
    goals: list[HighLevelGoal]

class LowLevelGoal(BaseModel):
    name: str
    description: str
    high_level_associated: HighLevelGoal

class LowLevelGoals(BaseModel):
    low_level_goals: list[LowLevelGoal]

class API(BaseModel):
    api_name: str
    api_path: str
    description: str
    request_type: str

class APIMapping(BaseModel):
    APIs: list[API]
    low_level_goal: LowLevelGoal